### ISSUE TITLE
main workflow transformation

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aktion#1]
the sample workflow:

```
workflow "knative test" {
  on = "push"
  resolves = [
    "First Action",
  ] 
}

action "First Action" {
  uses = "docker://centos"
  runs = "echo"
  env = {
    FOO = "BAR"
  }
  args = "Hello world"
}
```

Should at first translate into a `Task` and a `TaskRun` like:

```
apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
```

and:

```
apiVersion: pipeline.knative.dev/v1alpha1
kind: TaskRun
metadata:
  name: echo-hello-world-task-run
spec:
  taskRef:
    name: echo-hello-world
  trigger:
    type: manual
```
