### ISSUE TITLE
local `uses` example fails

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/aktion#27]
I tried to check the `uses` support:

https://github.com/triggermesh/aktion/blob/master/samples/test-local.workflow

with

```
aktion create -f samples/test-local.workflow -g https://github.com/sebgoa/cloudbuild -p | kubectl -n sebgoa apply -f -
```

when the pipeline run gets executed there is a validation error:

```
Status:
  Conditions:
    Last Transition Time:  2019-04-23T10:39:13Z
    Message:               invalid input resources: TaskRun's declared resources didn't match usage in Task: Didn't provide required values: [local-repo-test]
    Reason:                PipelineValidationFailed
    Status:                False
    Type:                  Succeeded
  Start Time:              2019-04-23T10:39:13Z
Events:
  Type    Reason                Age              From                 Message
  ----    ------                ----             ----                 -------
  Normal  PipelineRunSucceeded  1m (x2 over 1m)  pipeline-controller  PipelineRun completed successfully.
```

**Comment by sebgoa** [comment]
Does the error comes from the extra slash:

```
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: "2019-04-30T13:52:14Z"
  name: local-repo-test-pipeline
spec:
  params: null
  resources:
  - name: samples-test-images-git
    type: git
  - name: samples-test-images-image
    type: image
  tasks:
  - name: build-samples-test-images
    params:
    - name: pathToContext
      value: /workspace/local-repo-test//
...
```
